workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-4
      acceleratorType: NVIDIA_TESLA_T4
      acceleratorCount: 1
    replicaCount: 1
    pythonPackageSpec:
      executorImageUri: us-docker.pkg.dev/vertex-ai/training/pytorch-gpu.1-13:latest
      packageUris:
        - gs://flood-detection-data/packages/flood_detection_trainer-0.1.tar.gz
      pythonModule: src.train_vertex
      args:
        - --bucket=flood-detection-data
        - --epochs=20
        - --batch-size=8